### ISSUE TITLE
dockerizing IB gateway

### ISSUE THREAD

**Issue by gpernelle** [magic-carpet-ai/ib-gateway-docker#2]

**Comment by drusakov778** [comment]
this is a dead, 'ghost' repository, no work is being done on it. Currently IB Gateway is being run via mcai_ib repository, see: https://github.com/magic-carpet-ai/mcai_ib/blob/develop/scripts/ib_gateway_walkthrough.txt, and it is that repository (mcai_ib) which needs to be dockerized

**Comment by drusakov778** [comment]
correct issue: https://github.com/magic-carpet-ai/mcai_ib/issues/68

**Comment by gpernelle** [comment]
ok thank you, I am closing this one
